<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified" version="1.0">
  <xs:include schemaLocation="common.xsd"/>

  <xs:complexType name="ResolvedComputeType">
    <xs:all>
      <xs:element name="cpu" type="xs:positiveInteger"/>
      <xs:element name="memory" type="DataSizeType"/>
    </xs:all>
  </xs:complexType>

  <xs:complexType name="ResolvedOsType">
    <xs:all>
      <xs:element name="type" type="GuestOsType"/>
      <xs:element name="configuration_path" type="NonEmptyStringType" minOccurs="0"/>
    </xs:all>
  </xs:complexType>

  <xs:complexType name="RelationResultType">
    <xs:all>
      <xs:element name="display_name" type="NonEmptyStringType"/>
      <xs:element name="description" type="NonEmptyStringType"/>
      <xs:element name="mountable_resources" type="StringListType"/>
      <xs:element name="relations" type="StringListType"/>
      <xs:element name="requirement" type="NonEmptyStringType"/>
      <xs:element name="satisfied" type="xs:boolean"/>
      <xs:element name="message" type="xs:string" minOccurs="0"/>
    </xs:all>
  </xs:complexType>

  <xs:complexType name="RelationResultsType">
    <xs:sequence>
      <xs:element name="item" type="RelationResultType" minOccurs="0" maxOccurs="unbounded"/>
    </xs:sequence>
  </xs:complexType>

  <xs:element name="deployment-plan">
    <xs:complexType><xs:all>
      <xs:element name="model_version" type="xs:positiveInteger"/>
      <xs:element name="deployment" type="ConfigurationReferenceType"/>
      <xs:element name="guest" type="ConfigurationReferenceType"/>
      <xs:element name="host" type="ConfigurationReferenceType"/>
      <xs:element name="environment" type="ConfigurationReferenceType"/>
      <xs:element name="resolved_os" type="ResolvedOsType"/>
      <xs:element name="resolved_compute" type="ResolvedComputeType"/>
      <xs:element name="resolved_network_interfaces" type="DynamicMapType"/>
      <xs:element name="resolved_management_endpoint" type="NetworkServiceEndpointType"/>
      <xs:element name="resolved_mountable_resources" type="DynamicMapType"/>
      <xs:element name="relation_results" type="RelationResultsType"/>
      <xs:element name="warnings" type="StringListType"/>
    </xs:all></xs:complexType>
  </xs:element>
</xs:schema>
