<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
  <xs:include schemaLocation="common.xsd"/>

  <xs:complexType name="GuestOsConfigurationType">
    <xs:all>
      <xs:element name="description" type="NonEmptyStringType"/>
      <xs:element name="type" type="GuestOsType"/>
      <xs:element name="configuration_path" type="NonEmptyStringType" minOccurs="0"/>
    </xs:all>
  </xs:complexType>

  <xs:complexType name="GuestCpuConstraintType">
    <xs:all>
      <xs:element name="minimum" type="xs:positiveInteger" minOccurs="0"/>
      <xs:element name="default" type="xs:positiveInteger" minOccurs="0"/>
    </xs:all>
  </xs:complexType>

  <xs:complexType name="GuestComputeConfigurationType">
    <xs:all>
      <xs:element name="description" type="NonEmptyStringType"/>
      <xs:element name="cpu" type="GuestCpuConstraintType" minOccurs="0"/>
      <xs:element name="memory" type="DataSizeConstraintType" minOccurs="0"/>
    </xs:all>
  </xs:complexType>

  <xs:complexType name="GuestNetworkInterfacesType">
    <xs:all>
      <xs:element name="description" type="NonEmptyStringType"/>
      <xs:element name="items" type="DynamicMapType"/>
    </xs:all>
  </xs:complexType>

  <xs:complexType name="GuestMountableResourcesType">
    <xs:all>
      <xs:element name="description" type="NonEmptyStringType"/>
      <xs:element name="items" type="DynamicMapOneOrMoreType"/>
      <xs:element name="relations">
        <xs:complexType>
          <xs:sequence>
            <xs:element name="item" type="MountableResourceRelationConfigurationType" minOccurs="0" maxOccurs="unbounded"/>
          </xs:sequence>
        </xs:complexType>
      </xs:element>
    </xs:all>
  </xs:complexType>

  <xs:element name="guest-configuration">
    <xs:complexType>
      <xs:all>
        <xs:element name="model_version">
          <xs:simpleType><xs:restriction base="xs:positiveInteger"><xs:enumeration value="1"/></xs:restriction></xs:simpleType>
        </xs:element>
        <xs:element name="guest" type="EntityIdentityType"/>
        <xs:element name="os" type="GuestOsConfigurationType"/>
        <xs:element name="compute" type="GuestComputeConfigurationType"/>
        <xs:element name="network_interfaces" type="GuestNetworkInterfacesType"/>
        <xs:element name="mountable_resources" type="GuestMountableResourcesType"/>
      </xs:all>
    </xs:complexType>
  </xs:element>
</xs:schema>
