<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified" version="1.0">
  <xs:include schemaLocation="common.xsd"/>
  <xs:element name="guest-deployment-configuration">
    <xs:complexType><xs:all>
      <xs:element name="model_version" type="xs:positiveInteger"/>
      <xs:element name="deployment" type="EntityIdentityType"/>
      <xs:element name="guest" type="ConfigurationReferenceType"/>
      <xs:element name="host" type="ConfigurationReferenceType"/>
      <xs:element name="compute" type="DynamicMapType"/>
      <xs:element name="network_interfaces" type="DescribedItemsType"/>
      <xs:element name="management_endpoint_interface_binding" type="NetworkServiceInterfaceBindingType"/>
      <xs:element name="mountable_resources" type="DescribedItemsType"/>
    </xs:all></xs:complexType>
  </xs:element>
</xs:schema>
