<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified" version="1.0">
  <xs:include schemaLocation="common.xsd"/>
  <xs:element name="host-configuration">
    <xs:complexType><xs:all>
      <xs:element name="model_version" type="xs:positiveInteger"/>
      <xs:element name="environment" type="ConfigurationReferenceType"/>
      <xs:element name="host" type="EntityIdentityType"/>
      <xs:element name="management_endpoint" type="NetworkServiceEndpointType"/>
      <xs:element name="storage_devices" type="DynamicMapType"/>
      <xs:element name="storage_controllers" type="DynamicMapType"/>
      <xs:element name="storage_targets" type="DynamicMapType"/>
      <xs:element name="networks" type="DynamicMapType"/>
      <xs:element name="mountable_resource_interfaces" type="DynamicMapType"/>
      <xs:element name="defaults" type="DynamicMapType"/>
    </xs:all></xs:complexType>
  </xs:element>
</xs:schema>
