<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified" version="1.0">
  <xs:include schemaLocation="common.xsd"/>
  <xs:element name="shared-mountable-resource-configuration">
    <xs:complexType><xs:all>
      <xs:element name="model_version" type="xs:positiveInteger"/>
      <xs:element name="shared_mountable_resource" type="EntityIdentityType"/>
      <xs:element name="storage_class" type="StorageClassType"/>
      <xs:element name="representation" type="RepresentationType"/>
      <xs:element name="host" type="ConfigurationReferenceType"/>
      <xs:element name="host_storage_target" type="IdentifierType"/>
      <xs:element name="size" type="DataSizeType" minOccurs="0"/>
      <xs:element name="backend" type="BackendType" minOccurs="0"/>
      <xs:element name="host_mountable_resource_interface" type="IdentifierType" minOccurs="0"/>
    </xs:all></xs:complexType>
  </xs:element>
</xs:schema>
