<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
  <xs:complexType name="StringListType">
    <xs:sequence>
      <xs:element name="item" type="xs:string" minOccurs="0" maxOccurs="unbounded"/>
    </xs:sequence>
  </xs:complexType>
  <xs:element name="validation-report">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="valid" type="xs:boolean"/>
        <xs:element name="scope" type="xs:string"/>
        <xs:element name="deployment" type="xs:string" minOccurs="0"/>
        <xs:element name="validated_files" type="StringListType"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
</xs:schema>
